/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/graph-summary` | `/screens/graph-summary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/medication` | `/screens/journal/medication`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/symptoms` | `/screens/journal/symptoms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/vitals` | `/screens/journal/vitals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/models/Question`; params?: Router.UnknownInputParams; } | { pathname: `/models/Vitals`; params?: Router.UnknownInputParams; } | { pathname: `/styles/HomeStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/MedicationStyle`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/screens/graph-summary` | `/screens/graph-summary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/screens/journal/medication` | `/screens/journal/medication`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/screens/journal/symptoms` | `/screens/journal/symptoms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/screens/journal/vitals` | `/screens/journal/vitals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/models/Question`; params?: Router.UnknownOutputParams; } | { pathname: `/models/Vitals`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/HomeStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/MedicationStyle`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/screens/graph-summary${`?${string}` | `#${string}` | ''}` | `/screens/graph-summary${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/screens/journal/medication${`?${string}` | `#${string}` | ''}` | `/screens/journal/medication${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/screens/journal/symptoms${`?${string}` | `#${string}` | ''}` | `/screens/journal/symptoms${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/screens/journal/vitals${`?${string}` | `#${string}` | ''}` | `/screens/journal/vitals${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/models/Question${`?${string}` | `#${string}` | ''}` | `/models/Vitals${`?${string}` | `#${string}` | ''}` | `/styles/HomeStyles${`?${string}` | `#${string}` | ''}` | `/styles/MedicationStyle${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/graph-summary` | `/screens/graph-summary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/medication` | `/screens/journal/medication`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/symptoms` | `/screens/journal/symptoms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/screens/journal/vitals` | `/screens/journal/vitals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/models/Question`; params?: Router.UnknownInputParams; } | { pathname: `/models/Vitals`; params?: Router.UnknownInputParams; } | { pathname: `/styles/HomeStyles`; params?: Router.UnknownInputParams; } | { pathname: `/styles/MedicationStyle`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
